### ISSUE TITLE
getNumber return empty string

### ISSUE THREAD

**Issue by pixedd** [betsol/ng-intl-tel-input#1]
Hi,
I've got an issue with $element.intlTelInput('getNumber') which return an empty string instead of my model.

Working, while adding $timeout to the method getModelValue()

```javascript
          function getModelValue () {
            $timeout(function() {
              return $element.intlTelInput('getNumber');
            });
          }
```

**Comment by slavafomin** [comment]
Hey! Thanks for a report. I've noticed it too recently. Looks like some migration issue after new major release of the `intl-tel-input`. I'm going to look into this. Until now, you can use `7.x` version.

**Comment by pixedd** [comment]
Hi, thanks for your feedback.
I'm currently using : International Telephone Input v7.1.1

Thanks ;)

**Comment by slavafomin** [comment]
Just to confirm. Do you encounter the problem with `7.x` version of the `intl-tel-input`?

**Comment by pixedd** [comment]
Yes, i do encounter the problem with 7.1.1 of intel-tel-input.

**Comment by slavafomin** [comment]
Hello @pixedd!

I've done a pretty heavy refactoring of the module and improved it's stability with both `7.x` and `8.x` versions of the `intl-tel-input`. Please see [the demo](http://betsol.github.io/ng-intl-tel-input/).

Could you please update your dependency and tell me if it works for you alright?

Cheers!

**Comment by pixedd** [comment]
Hi @slavafomin !

I update my bower package with your directive 1.1.0 and it looks like it's working great with 7.1.1of intel-tel-input.

Good work, thanks ;)

**Comment by slavafomin** [comment]
That's nice to hear! I'm happy to help = )
Good luck!
