### ISSUE TITLE
Webpack build not working

### ISSUE THREAD

**Issue by dganoff** [betsol/ng-intl-tel-input#15]
I'm in the process of migrating to webpack from a Grunt build system that simply places this library along with its dependencies (jQuery, intl-tel-input, utils.js) into a concatenated JS file and then loads it on the page with a `<script>` tag. Since I'm trying to use the path of least resistance during this migration, I've decided to use the `script-loader` which loads JS files as if they were loaded via a `<script>` tag. 

I can verify that `jQuery`, `intl-tel-input` plugin, `utils.js` and the `ng-intl-tel-input` module have all loaded on the page, but when the `ng-intl-tel-input` directive tries to initialize in the `link` function, I keep getting the error `ng-intl-tel-input: intl-tel-input jQuery plugin must be loaded, skipping directive initialization`. 

Here is the relevant portion of my `app.js` entry file that loads the aforementioned scripts:
``` javascript
require("script!../../node_modules/jquery/dist/jquery.js");
...
require("script!../../node_modules/intl-tel-input/build/js/intlTelInput.js");
require("script!../../node_modules/intl-tel-input/build/js/utils.js");
...
require("betsol-ng-intl-tel-input");
...
angular.module("app", ["betsol.intlTelInput"]);
```

Has anyone else successfully implemented this module using a webpack build system? I know these files work because I can manually load them on the page with `<script>` tags and the directive functions correctly.

**Comment by slavafomin** [comment]
Hello! Thank you for your interest in this module!

I've never tried to merge all scripts to a single file this way, I tend to include some vendor modules individually only on pages where it's necessary.

It looks like you have a problem with order of scripts execution. How do you bootstrap Angular application?

Your Angular bootstrapping code must be called after both jQuery and intlTelInput plugin are loaded and initialized.

The one way is to place your application initialization code into a global function and call it before the `</body>` tag.

**Comment by slavafomin** [comment]
I'm going to close this issue as outdated. Please, tell me if you still have a problem, so I can re-open it for further discussion. Thanks.
