### ISSUE TITLE
jQuery plugin must be loaded, skipping directive initialization

### ISSUE THREAD

**Issue by meshal500** [betsol/ng-intl-tel-input#16]
Hello,

I am getting this in the console :

ng-intl-tel-input: intl-tel-input jQuery plugin must be loaded, skipping directive initialization

What can be causing this?

**Comment by yassinemri** [comment]
you must load[ intlTelInput.js](https://github.com/jackocnr/intl-tel-input) first

**Comment by tnusraddinov** [comment]
same issue

**Comment by slavafomin** [comment]
Hello! Thank you for your interest in this module!

Are you loading original plugin prior to this integration module?

**Comment by tnusraddinov** [comment]
including all files below works for me

css files:
intl-tel-input/build/css/intlTelInput.css

js files:
jquery/dist/jquery.js
angular/angular.js
intl-tel-input/build/js/intlTelInput.js
intl-tel-input/build/js/utils.js
ng-intl-tel-input/dist/ng-intl-tel-input.js

Note: ng-intl-tel-input = "version": "2.0.0", intl-tel-input="version": "9.0.14" and jquery = "version": "3.2.0"

**Comment by slavafomin** [comment]
Glad to hear it. I'm going to close this.

**Comment by GloomyStranger** [comment]
@tnusraddinov , can you suggest, where you have include these files?

**Comment by slavafomin** [comment]
@GloomyStranger I would suggest using npm and something like Webpack to bundle all the files together.

**Comment by GloomyStranger** [comment]
@slavafomin yeah, I`ve tried, but don`t get any luck, would be cool if you can show any of working ways

**Comment by slavafomin** [comment]
@GloomyStranger What exact problem do you have with the approach I've mentioned?

**Comment by GloomyStranger** [comment]
@slavafomin` ng-intl-tel-input: intl-tel-input jQuery plugin must be loaded, skipping directive initialization` got this and regular input field instead of lib custom input

**Comment by slavafomin** [comment]
@GloomyStranger You must make sure that all libraries are loaded. I would suggest to examine the bundle and to see if all modules are properly exported. Maybe some adjustments must be needed in Webpack configuration to make it work. I'm not using the Angular.js for at least two years now, so I don't have a working example, which I could share, sorry.

**Comment by GloomyStranger** [comment]
@slavafomin Im good know what you mean, Angularjs is old but I`m supporting big old project so there I havent any choice
