### ISSUE TITLE
Error: $compile:multidir Multiple Directive Resource Contention

### ISSUE THREAD

**Issue by grishmadoshi** [betsol/ng-intl-tel-input#17]
I have created directive in custom componenet and used this ng-intl-tel-input directive in that
and using my custom directive in test page is ok, but in my ionic app with angular it is giving 
Error: $compile:multidir Multiple Directive Resource Contention
with below details
Multiple directives [input (module: myionicapp), intlTelInput] asking for new/isolated scope on: <input id="phoneNumber" name="phoneNumber" class="form-control ng-pristine ng-untouched ng-valid" ng-model="phoneNum" intl-tel-input="" intl-tel-input-controller="phoneNumberCtrl" type="tel">

**Comment by slavafomin** [comment]
Hello! Thank you for your interest in this module!

It looks like your are (or ionic itself) adding some other directive to your input element and Angular.js doesn't allow to have two directives with isolated scopes on a single DOM element. This is a limitation of Angular.js I'm afraid.

**Comment by grishmadoshi** [comment]
Hello slavafomin, Thanks for replying.

As per you mentioned, I checked and found another directive in ionic app, i commented that to test but now i am facing another issue:
ng-intl-tel-input: intl-tel-input jQuery plugin must be loaded, skipping directive initialization

I checked in code and have referenced all js file correctly.

**Comment by slavafomin** [comment]
Load you page please and in browser's console write the following: `$('element-selector').intlTelInput;` where `element-selector` is valid selector for your input element. And paste here the output.

**Comment by slavafomin** [comment]
I'm going to close this as outdated.
