### ISSUE TITLE
display as filter ?

### ISSUE THREAD

**Issue by pixedd** [betsol/ng-intl-tel-input#18]
Hi there !

Is there a way to use your directive as a filter to display formated phone number in paragraph for example:

```<p>{{phone | phone}}</p>```

?

**Comment by slavafomin** [comment]
Hello! Thank you for your interest in this module!

I don't believe it's possible. Actually, the purpose of this module is just to integrate `intl-tel-input` plugin. It's out of scope of this module to introduce additional functionality. Sorry.
