### ISSUE TITLE
ng-Model not populating the value

### ISSUE THREAD

**Issue by tryingtochange** [betsol/ng-intl-tel-input#19]
I'm using this module inside an ng-if condition.

I have used ng-model="model.phoneNumber", I still get an undefined as value.
Also when I set the intl-tel-input-controller="myIntlTelInputCtrl" and in controller I have $scope.myIntlTelInputCtrl; I get "getNumber()" of undefined as the API is not getting initialised.

However, intl-tel-input-options="{ onlyCountries: ['us', 'in'] }" is working.

**Comment by slavafomin** [comment]
Hello! Thank you for your interest in this module!

Could you please re-create the issue using [Plunker](https://plnkr.co/edit/?p=catalogue)?

**Comment by slavafomin** [comment]
I'm going to close this as outdated.
