### ISSUE TITLE
Failed to instantiate module due to main path in bower file

### ISSUE THREAD

**Issue by jordandotme** [betsol/ng-intl-tel-input#2]
In `bower.json` the following path causes an instantiation error:

`"main": "dist/betsol-ng-intl-tel-input.js"`

I'm using gulp inject to automatically populate any bower script dependencies. It seems that the above line doesn't work unless I point it to the scripts directory within dist, like so:

``"main": "dist/scripts/betsol-ng-intl-tel-input.js"`

Have you ever had any issues regarding this?

**Comment by slavafomin** [comment]
Yes, that makes perfect sense. Could you please send a PR to fix this? I'll appreciate it )

**Comment by slavafomin** [comment]
Thanks, for a PR! You will have to use #master version for now, until I will be able to create a tag. I'm in the middle of transferring my office right now ))
