### ISSUE TITLE
some of numbers showing as invalid number but it is valid number 

### ISSUE THREAD

**Issue by arunrepala** [betsol/ng-intl-tel-input#21]
for example '8919153888' is valid number in india. But it is treating as invalid number

**Comment by slavafomin** [comment]
Hello! Thank you for your interest in this module!

However, this library is just providing integration of [intl-tel-input](https://github.com/jackocnr/intl-tel-input) with AngularJS. You should file such issues with the original library.

**Comment by antonbuks** [comment]
The issue is that this library is using an extemely outdated version of the original library, the issue has long been resolved in the original.
