### ISSUE TITLE
Non-Assignable error in directive

### ISSUE THREAD

**Issue by jordandotme** [betsol/ng-intl-tel-input#4]
I receive the following error when using the directive:

`Expression 'undefined' used with directive 'intlTelInput' is non-assignable!`

Following [this](https://docs.angularjs.org/error/$compile/nonassign) document, it seems the issue is in the scope properties: 
```
scope: {
    intlTelInputOptions: '=',
    intlTelInputController: '='
}
```

Making the binding optional fixes the error:
```
scope: {
    intlTelInputOptions: '=?',
    intlTelInputController: '=?'
}
```
Can you confirm that this is a viable solution? If I can configure the module globally, It makes sense to make them optional.

**Comment by slavafomin** [comment]
Thank you @jordandotme!

That makes perfect sense, it was an oversight from my part. I've fixed the issue in the **#master** branch and will create an immediate release today.
