### ISSUE TITLE
Cannot set property 'phoneNumber' of undefined

### ISSUE THREAD

**Issue by szukaiLee** [betsol/ng-intl-tel-input#5]
Everything working fine, but have this error.

''Cannot set property 'phoneNumber' of undefined''

**Comment by szukaiLee** [comment]
I found that angular 1.2.29 do not have $validators, please add in support for angular 1.2.29

**Comment by slavafomin** [comment]
Hello @szukaiLee!

Thank you for your suggestion! I've update the module to also support legacy versions of Angular.js.

I'm going to issue an immediate release today, feel free to update you packages and test if it works correctly.

Have a great day!

**Comment by slavafomin** [comment]
I'm closing this now, if you have any other issues or questions, please let me know ;)
