### ISSUE TITLE
Current intl-tel-input version does not work well

### ISSUE THREAD

**Issue by jordandotme** [betsol/ng-intl-tel-input#9]
The current version of intl-tel-input (7.1.1) seems to be broken when using certain configurations. I noticed that you [recently downgraded](https://github.com/betsol/ng-intl-tel-input/commit/69bc0fec7374020a7c6961f3297aeeab40ff9586#diff-0a08a7565aba4405282251491979bb6bL15) to this version from 8.4.6 (current release). 

Any reason for this change?

**Comment by slavafomin** [comment]
Hello @jordandotme!

I've not "downgraded", I've just extended the supported versions of the core library. You can use any version of `intl-tel-input` as you like, starting from `7.1.1`.

If you have problems with one of the supported versions please file the detailed bug report, I will be glad to look into it ;)

**Comment by aaronrenner** [comment]
I think the version string for the intl-tel-input dependency should be `>= 7.1.1` to allow upgrading to the `8.x` versions. The caret operator [prevents major version bumps](http://stackoverflow.com/a/22345808).

**Comment by slavafomin** [comment]
Thanks @aaronrenner for pointing this out. I've missed it.

I've replaced the version string with this one: `7.1.1 - 8.*` in order to support both 7 and 8 versions. We will have to play safe here with next major versions of the core library.

Cheers!
